---
rvm:
  - 2.6.3
env:
  matrix:
    - PUPPET_VERSION=5.0
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
    - rvm: 2.6.3
      env: PUPPET_VERSION=5.0
    # Acceptance tests
    - rvm: 2.6.3
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
      script: bundle exec rake beaker
      services: docker
      bundler_args: --without development
    - rvm: 2.6.3
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-18.04
      script: bundle exec rake beaker
      services: docker
      bundler_args: --without development
bundler_args: --without system_tests development
sudo: false
